import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()



LLM_RESPONSE_RETRY_LIMIT = 3
LLM_RATE_LIMIT_MAX_ATTEMPTS = 3
LLM_RATE_LIMIT_BACKOFF_BASE_SECONDS = 1.0
LLM_RATE_LIMIT_BACKOFF_MAX_SECONDS = 30.0
LLM_RATE_LIMIT_MAX_DELAY_SECONDS = 1800.0
LLM_RESPONSE_TIMEOUT_SECONDS = 150
MIN_COOLDOWN_TIME = 0.0
MAX_COOLDOWN_TIME = 30.0
MIN_FEEDBACK_LEN = 10
_JSON_REPAIR_TRIES = 2
RETRIEVAL_TIMEOUT_SECONDS = 10
EMBEDDING_ENCODING_TIMEOUT_SECONDS = 5
